default:
  iface1:
    name: "wlanx"
    host: 0.0.0.0
    gateway: 0.0.0.0
  iface2:
    name: "wlany"
    host: 0.0.0.0
    gateway: 0.0.0.0
  server:
    name: "quic.smalldragon.net"
    host: 0.0.0.0
  single:
    ssid1: "ssid1"
    pass1: "password1"
    ssid2: "ssid2"
    pass2: "password2"
