default:
  iface1:
    name: "wlanx"
    host: 0.0.0.0
    gateway: 0.0.0.0
  iface2:
    name: "wlany"
    host: 0.0.0.0
    gateway: 0.0.0.0
  server:
    name: "quic.smalldragon.net"
    host: 0.0.0.0