default:
  iface1:
    name: "wlan0"
    host: 192.168.34.50
    gateway: 192.168.34.1
  iface2:
    name: "wlan1"
    host: 192.168.93.13
    gateway: 192.168.93.1
  server:
    name: "quic.smalldragon.net"
    host: 0.0.0.0
  single:
    ssid1: "ssid1"
    pass1: "password1"
    ssid2: "ssid2"
    pass2: "password2"
